#!/bin/sh
#

RED='\033[1;31m'
GREEN='\033[1;32m'
PINK='\033[1;35m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}Running pre-commit hook...${NC}"
npm run lint-staged
if [ $? -ne 0 ]; then
  echo -e "${RED} lint failed, Please fix error and restage the changes${NC}"
  exit 1
fi
npm run build
if [ $? -ne 0 ]; then
  echo -e "${RED} Build failed, Please fix error and restage the changes${NC}"
  exit 1
fi

echo -e "${GREEN}pre-commit hook passed${NC}, and here's a joke for you: ${PINK}"
if curl -s 'https://icanhazdadjoke.com/' -H 'Accept: text/plain'; then
    echo -e "${NC}"
else
    echo -e "${YELLOW}Could not fetch joke, kindly check your internet connection${NC}"
fi

echo -e "${GREEN}Finished${NC}"
